image: alpine

stages:
  - test
  - deploy
  - release

variables:
  LOWER_PROJECT_NAME: "shm_stream"
  UPPER_PROJECT_NAME: "SHM_STREAM"
  SECURE_LOG_LEVEL: debug

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
dependency_scanning:
  needs: []
sast:
  needs: []

line count:
  stage: test
  needs: []
  image: registry.gitlab.com/musicscience37projects/docker/cloc-docker
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=extern,line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./include ./src
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"
  interruptible: true

pre-commit:
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang16
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.11
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    key:
      prefix: cache-${CI_JOB_NAME}
      files:
        - poetry.lock
    paths:
      - .venv
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
  interruptible: true

test release:
  stage: test
  needs: []
  parallel:
    matrix:
      - COMPILER_TYPE: ["gcc12"]
        IMAGE_PATH: "musicscience37/gcc-ci"
        CXX_STANDARD: 14
      - COMPILER_TYPE: ["clang16"]
        IMAGE_PATH: "musicscience37/clang-ci"
        CXX_STANDARD: 14
  image: ${IMAGE_PATH}:${COMPILER_TYPE}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_TYPE: Release
    BUILD_DIR: build_${COMPILER_TYPE}_release
    CCACHE_DIR: ${CI_PROJECT_DIR}/.cache
    CCACHE_COMPILERCHECK: content
  before_script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.11
    - poetry install
    - mkdir $BUILD_DIR
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=ON
      -D${UPPER_PROJECT_NAME}_TEST_BENCHMARKS=ON
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_TEST_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
      -DCMAKE_CXX_STANDARD=$CXX_STANDARD
    - cmake --build .
    - ctest -V
  cache:
    key:
      prefix: cache-${CI_JOB_NAME}
      files:
        - poetry.lock
    paths:
      - .cache
      - .venv
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"
  interruptible: true

test debug:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: ["gcc12"]
        IMAGE_PATH: "musicscience37/gcc-ci"
        CXX_STANDARD: 14
      - COMPILER_TYPE: ["clang16"]
        IMAGE_PATH: "musicscience37/clang-ci"
        CXX_STANDARD: 14
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_${COMPILER_TYPE}_debug
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -DCMAKE_CXX_STANDARD=$CXX_STANDARD
    - cmake --build .
    - ctest -V

static analysis:
  extends: test debug
  parallel:
    matrix:
      - COMPILER_TYPE: "clang16"
        IMAGE_PATH: "musicscience37/clang-ci"
        CXX_STANDARD: 14
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_static_analysis
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=ON
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CPP_WARNINGS:BOOL=ON
      -DCMAKE_CXX_STANDARD=$CXX_STANDARD
    - cd ..
    - poetry run clang-tidy-checker -b ${BUILD_DIR}

clang coverage:
  extends: test debug
  parallel:
    matrix:
      - COMPILER_TYPE: "clang16"
        IMAGE_PATH: "musicscience37/clang-ci"
        CXX_STANDARD: 14
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=Debug
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
    - poetry run lcov_cobertura $BUILD_DIR/coverage/coverage --output $BUILD_DIR/coverage.xml
  coverage: '/[^\s]+%\s+\d+\s+\d+\s+\s[^\s]+%/'
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
      coverage_report:
        coverage_format: cobertura
        path: $BUILD_DIR/coverage.xml
    when: always
    expire_in: "1 mos"

clang-16-asan-ubsan:
  extends: test debug
  parallel:
    matrix:
      - COMPILER_TYPE: "clang16"
        IMAGE_PATH: "musicscience37/clang-ci"
        CXX_STANDARD: 14
  variables:
    BUILD_DIR: build_clang_asan_ubsan
    ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=Debug
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_AUSAN:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cmake --build .
    - ctest -V

doc:
  stage: test
  needs: []
  image: musicscience37/sphinx-doxygen:clang16
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_TYPE: Release
    BUILD_DIR: build_doc
  before_script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.11
    - poetry install
    - mkdir $BUILD_DIR
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -D${UPPER_PROJECT_NAME}_BUILD_DOC:BOOL=ON
    - cmake --build . --target ${LOWER_PROJECT_NAME}_doc
  artifacts:
    paths:
      - build_doc/doc
    when: always
    expire_in: "3 mos"
  interruptible: true

pages:
  stage: deploy
  only:
    - develop
  needs:
    - doc
    - clang coverage
    - line count
  dependencies:
    - doc
    - clang coverage
    - line count
  script:
    - rm -rf public
    - mv build_doc/doc/html public
    - mv build_clang_coverage/coverage/html public/coverage
    - mv line_count public/line_count
  artifacts:
    paths:
      - public
