image: ubuntu:focal

stages:
  - test
  - deploy
  - release

variables:
  LOWER_PROJECT_NAME: "shm_stream"
  UPPER_PROJECT_NAME: "SHM_STREAM"
  CONAN_PACKAGE_NAME: "cpp-shm-stream"
  CONAN_USER: "MusicScience37"
  SECURE_LOG_LEVEL: debug

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
dependency_scanning:
  needs: []
sast:
  needs: []
license_scanning:
  needs: []

.retry setting:
  retry: 1

line count:
  extends: .retry setting
  stage: test
  needs: []
  image: registry.gitlab.com/musicscience37projects/docker/cloc-docker
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=extern,line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./include
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"
  interruptible: true

pre-commit:
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang13
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    key:
      prefix: cache-${CI_JOB_NAME}
      files:
        - poetry.lock
    paths:
      - .venv
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
  interruptible: true

.release-test-base:
  extends: .retry setting
  stage: test
  needs: []
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CCACHE_DIR: ${CI_PROJECT_DIR}/.cache
    CCACHE_COMPILERCHECK: content
    CONAN_USER_HOME: ${CI_PROJECT_DIR}
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Release
  before_script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - poetry run conan profile new --force --detect default
    - poetry run conan profile update settings.compiler.libcxx=${CONAN_STD_CPP_LIB} default
    - poetry run conan install --build missing -s build_type=${CMAKE_BUILD_TYPE} -o requirements_for_tests=True ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=OFF
      -D${UPPER_PROJECT_NAME}_TEST_BENCHMARKS=OFF
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=OFF
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
  cache:
    key:
      prefix: cache-${CI_JOB_NAME}
      files:
        - poetry.lock
    paths:
      - .cache
      - .conan
      - .venv
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"
  interruptible: true

.bench-base:
  extends: .release-test-base
  variables:
    CMAKE_BUILD_TYPE: Release
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=OFF
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=OFF
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=ON
      -D${UPPER_PROJECT_NAME}_TEST_BENCHMARKS=ON
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_TEST_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

static analysis:
  extends: .release-test-base
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang13
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_DIR: build_static_analysis
    CONAN_STD_CPP_LIB: "libc++"
    CMAKE_BUILD_TYPE: Debug
  script:
    - cmake -S ./ -B ${BUILD_DIR}
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=ON
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CPP_WARNINGS:BOOL=ON
    - poetry run clang-tidy-checker -b ${BUILD_DIR}

clang coverage:
  extends: .release-test-base
  image: musicscience37/clang-ci:clang13
  variables:
    BUILD_DIR: build_clang_coverage
    CONAN_STD_CPP_LIB: "libc++"
    CMAKE_BUILD_TYPE: Debug
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
    - poetry run lcov_cobertura $BUILD_DIR/coverage/coverage --output $BUILD_DIR/coverage.xml
  coverage: '/[^\s]+%\s+\d+\s+\d+\s+\s[^\s]+%/'
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
      coverage_report:
        coverage_format: cobertura
        path: $BUILD_DIR/coverage.xml
    when: always
    expire_in: "1 mos"

gcc-10-debug:
  extends: .release-test-base
  image: musicscience37/gcc-ci:gcc10
  variables:
    BUILD_DIR: build_gcc10_debug
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Debug

gcc-10-release:
  extends: .release-test-base
  image: musicscience37/gcc-ci:gcc10
  variables:
    BUILD_DIR: build_gcc10_release
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Release

gcc-10-bench:
  extends: .bench-base
  image: musicscience37/gcc-ci:gcc10
  variables:
    BUILD_DIR: build_gcc10_bench
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Release

gcc-12-debug:
  extends: .release-test-base
  image: musicscience37/gcc-ci:gcc12
  variables:
    BUILD_DIR: build_gcc12_debug
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Debug

gcc-12-release:
  extends: .release-test-base
  image: musicscience37/gcc-ci:gcc12
  variables:
    BUILD_DIR: build_gcc12_release
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Release

gcc-12-bench:
  extends: .bench-base
  image: musicscience37/gcc-ci:gcc12
  variables:
    BUILD_DIR: build_gcc12_bench
    CONAN_STD_CPP_LIB: "libstdc++11"
    CMAKE_BUILD_TYPE: Release

clang-13-debug:
  extends: .release-test-base
  image: musicscience37/clang-ci:clang13
  variables:
    BUILD_DIR: build_clang13_debug
    CONAN_STD_CPP_LIB: "libc++"
    CMAKE_BUILD_TYPE: Debug

clang-13-release:
  extends: .release-test-base
  image: musicscience37/clang-ci:clang13
  variables:
    BUILD_DIR: build_clang13_release
    CONAN_STD_CPP_LIB: "libc++"
    CMAKE_BUILD_TYPE: Release

clang-13-bench:
  extends: .bench-base
  image: musicscience37/clang-ci:clang13
  variables:
    BUILD_DIR: build_clang13_bench
    CONAN_STD_CPP_LIB: "libc++"
    CMAKE_BUILD_TYPE: Release

clang-13-asan-ubsan:
  extends: .release-test-base
  image: musicscience37/clang-ci:clang13
  variables:
    BUILD_DIR: build_clang_asan_ubsan
    ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
    CONAN_STD_CPP_LIB: "libc++"
    CMAKE_BUILD_TYPE: Debug
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_AUSAN:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

# TODO
.clang-13-conan:
  extends: .retry setting
  needs: []
  image: musicscience37/clang-ci:clang13
  variables:
    CONAN_CHANNEL: "testing"
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - poetry run conan profile new --force --detect default
    - poetry run conan profile update settings.compiler.libcxx=libc++ default
    - poetry run conan create --build missing --test-folder tests/conan_package . ${CONAN_USER}/${CONAN_CHANNEL}
  interruptible: true

# TODO
.clang-13-conan-release:
  extends: .retry setting
  stage: deploy
  needs: []
  image: musicscience37/clang-ci:clang13
  variables:
    CONAN_CHANNEL: "stable"
  script:
    - mkdir -p .venv
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
    - poetry run conan profile new --force --detect default
    - poetry run conan profile update settings.compiler.libcxx=libc++ default
    - poetry run conan remote add -f cpp-shm-stream https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/conan
    - poetry run conan create --build missing --test-folder tests/conan_package . ${CONAN_USER}/${CONAN_CHANNEL}
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} poetry run conan upload -r cpp-shm-stream ${CONAN_PACKAGE_NAME} -c --all
  only:
    - tags

.msvc-base:
  extends: .release-test-base
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: test
  needs: []
  dependencies: []
  variables:
    CONAN_USER_HOME: C:\Users\gitlab_runner
    # Workaround in https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=conan_use_always_short_paths#short-paths
    CONAN_USE_ALWAYS_SHORT_PATHS: 1
    # Workaround in https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997
    PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  before_script:
    - (mv ${CI_PROJECT_DIR}/.conan C:\Users\gitlab_runner -Force)
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python --version=3.10.8 -y
    - choco install ccache -y
    - RefreshEnv
    - ccache --version
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry env use 3.10
    - poetry install
  script:
    # Changed in below.
    - ls
  after_script:
    - (mv C:\Users\gitlab_runner\.conan ${CI_PROJECT_DIR} -Force)
  allow_failure: true
  interruptible: true

# TODO
.msvc-debug:
  extends: .msvc-base
  variables:
    BUILD_DIR: build_msvc_debug
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - poetry run conan profile new --force --detect default
    - poetry run conan install --build missing -o requirements_for_tests=True -s build_type=Debug ..
    - cd ../
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DSHM_STREAM_TESTING:BOOL=ON
      -DSHM_STREAM_ENABLE_UNIT_TESTS=ON
      -DSHM_STREAM_ENABLE_INTEG_TESTS=OFF
      -DSHM_STREAM_ENABLE_BENCH=OFF
      -DSHM_STREAM_TEST_BENCHMARKS=OFF
      -DSHM_STREAM_BUILD_EXAMPLES=OFF
      -DSHM_STREAM_TEST_EXAMPLES=OFF
      -DSHM_STREAM_WRITE_JUNIT:BOOL=ON
      -DSHM_STREAM_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build . --config Debug --parallel 3
    - ctest -V --build-config Debug

# TODO
.msvc-release:
  extends: .msvc-base
  variables:
    BUILD_DIR: build_msvc
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - poetry run conan profile new --force --detect default
    - poetry run conan install --build missing -o requirements_for_tests=True -s build_type=Release ..
    - cd ../
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DSHM_STREAM_TESTING:BOOL=ON
      -DSHM_STREAM_ENABLE_UNIT_TESTS=ON
      -DSHM_STREAM_ENABLE_INTEG_TESTS=OFF
      -DSHM_STREAM_ENABLE_BENCH=OFF
      -DSHM_STREAM_TEST_BENCHMARKS=OFF
      -DSHM_STREAM_BUILD_EXAMPLES=OFF
      -DSHM_STREAM_TEST_EXAMPLES=OFF
      -DSHM_STREAM_WRITE_JUNIT:BOOL=ON
      -DSHM_STREAM_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build . --config Release --parallel 3
    - ctest -V --build-config Release

doc:
  extends: .release-test-base
  stage: test
  needs: []
  image: musicscience37/sphinx-doxygen:clang13
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CMAKE_BUILD_TYPE: Release
    BUILD_DIR: build_doc
  script:
    - cmake -S ./ -B build_doc
      -D${UPPER_PROJECT_NAME}_BUILD_DOC:BOOL=ON
    - cmake --build build_doc --target ${LOWER_PROJECT_NAME}_doc
  artifacts:
    paths:
      - build_doc/doc
    when: always
    expire_in: "3 mos"
  interruptible: true

pages:
  extends: .retry setting
  stage: deploy
  only:
    - develop
  needs:
    - doc
    - clang coverage
    - line count
  dependencies:
    - doc
    - clang coverage
    - line count
  script:
    - rm -rf public
    - mv build_doc/doc/html public
    - mv build_clang_coverage/coverage/html public/coverage
    - mv line_count public/line_count
  artifacts:
    paths:
      - public
