set(SOURCE_FILES
    shm_stream/blocking_stream_test.cpp
    shm_stream/c_interface/c_headers.c
    shm_stream/c_interface/error_codes_test.cpp
    shm_stream/c_interface/translate_error_test.cpp
    shm_stream/details/atomic_index_pair_test.cpp
    shm_stream/details/blocking_bytes_queue_test.cpp
    shm_stream/details/light_bytes_queue_test.cpp
    shm_stream/details/smart_ptr_test.cpp
    shm_stream/light_stream_test.cpp
    shm_stream/string_view_test.cpp
)
