#include "shm_stream/c_interface/c_headers.c"  // NOLINT(bugprone-suspicious-include)
#include "shm_stream/c_interface/error_codes_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "shm_stream/c_interface/translate_error_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "shm_stream/details/atomic_index_pair_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "shm_stream/details/no_wait_bytes_queue_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "shm_stream/no_wait_stream_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "shm_stream/string_view_test.cpp"  // NOLINT(bugprone-suspicious-include)
