set(SOURCE_FILES
    shm_stream/c_interface/atomic_stream_internal.cpp
    shm_stream/c_interface/blocking_stream_common.cpp
    shm_stream/c_interface/blocking_stream_internal.cpp
    shm_stream/c_interface/blocking_stream_reader.cpp
    shm_stream/c_interface/blocking_stream_writer.cpp
    shm_stream/c_interface/error_codes.cpp
    shm_stream/c_interface/light_stream_common.cpp
    shm_stream/c_interface/light_stream_internal.cpp
    shm_stream/c_interface/light_stream_reader.cpp
    shm_stream/c_interface/light_stream_writer.cpp
)
